name: CI - Real Time Sentiment Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Download spaCy model
        run: python -m spacy download en_core_web_sm

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Start FastAPI server
        run: uvicorn app.main:app --host 0.0.0.0 --port 8000 &
        
      - name: Wait for server to be ready
        run: |
          for i in {1..10}; do
            if curl -s http://127.0.0.1:8000/docs > /dev/null; then
              echo "Server is up!"
              break
            fi
            echo "Waiting for server..."
            sleep 2
          done

      - name: Test API root
        run: curl http://127.0.0.1:8000

