name: CI - Real Time Sentiment Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Download spaCy model
        run: python -m spacy download en_core_web_sm

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Test FastAPI startup
        run: |
          pip install uvicorn
          uvicorn app.main:app --host 127.0.0.1 --port 8000 &
          sleep 5
          curl -f http://127.0.0.1:8000/docs
